baseURL = 'https://novocestina.cz/'
languageCode = 'CS_cz'
title = 'Novočeština'
theme= 'roxo-hugo'
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Domů"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Proč prohoha?!"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Gramatika"
    url     = "gramatika"
    weight  = 3
  [[menu.nav]]
    name    = "Články"
    url     = "clanky"
    weight  = 4
#  [[menu.nav]]
#    name    = "Napište nám"
#    url     = "contact"
#    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = ["css/novocestina.css"]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Novočeština - více času na podstatnější věci"
  author = "Novočeština"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Jméno"
    placeholder_last_name         = "Příjmení"
    placeholder_email             = "Email"
    placeholder_project_type      = "Předmět"
    placeholder_about_the_project = "Zpráva"
    send_message                  = "Odeslat"

    [[params.contactForm.projectType]]
      value = "fact"
      title  = "Připomínka"
    [[params.contactForm.projectType]]
      value = "ok"
      title  = "Pochavala"
    [[params.contactForm.projectType]]
      value = "ko"
      title  = "Kritika"

  # Navbar Action Button
  # [params.navAction]
  #   status  = true
  #   name    = "Napište nám"
  #   url     = "contact"


  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Novočeština"
    tagline               = "PRAGMATICKÝ PŘÍSTUP K JAZIKU"
    primary_button        = "Jak odstranit Y"
    primary_button_url    = "clanky/hledani-rovnovahy"
    secondary_button      = "Nová pravidla"
    secondary_button_url  = "gramatika"

  [params.blog]
    read_more             = "read more"

  [params.portfolio]
    enable    = true
    title     = "ZÁKLADNÍ KAMENY NOVOČEŠŤINY"
    subtitle  = "Když nevíš jaké i/y, tak píšeš měkké"
    view_project = "zobrazit"
    more_works = "ostatní pravidla"
    scroll_down = "dolů"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Líbí?"
    primary_button      = "Líbí!"
    primary_button_url  = "contact"
    secondary_button    = "Kejda!"
    secondary_button_url = "gramatika"

  [params.footer]
    params.footer.qr_print = true
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Chcete se přidat do týmu?"
      address = "Napište nám"
      #phone   = "409-896-1444"
      email   = "novocestina@seznam.cz"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Rocestník"
        [[params.footer.sitemap.link]]
          name = "Proč?!"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Gramatika"
          url  = "gramatika"
        [[params.footer.sitemap.link]]
          name = "Články"
          url  = "clanky"
        [[params.footer.sitemap.link]]
          name = "Připomínky"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Socky"
        [[params.footer.social.link]]
          name = "Seznam Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Náš cíl:"
        description = "Zjednodušit češtinu, ať je čas na podstatnější věci"
      [params.footer.back_to_top]
        description = "Zpátky nahoru"
